source("R/config.R")
p27 <- readRDS(file.path(DIR_DERIVED, "panel_27.rds"))
cat("totexp_y1 summary:\n"); print(summary(p27$totexp_y1))
cat("totexp_y2 summary:\n"); print(summary(p27$totexp_y2))
cat("n totexp_y2 NA:", sum(is.na(p27$totexp_y2)), "\n")
cat("n totexp_y1 NA:", sum(is.na(p27$totexp_y1)), "\n")
f_cols <- grep("^f_", names(p27), value = TRUE)
all_na <- sapply(p27[f_cols], function(x) all(is.na(x)))
cat("n f_* columns fully NA:", sum(all_na), "of", length(f_cols), "\n")
cat("sample f_* names:\n"); print(head(f_cols, 20))
